const field = [
    { id: 0,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 1,field_name: 'Sports Grill', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 2,field_name: 'JAFF', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 3,field_name: 'Abahani', sport: 'cricket, football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 4,field_name: 'Sheikh Jamal', sport: 'cricket, football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 5,field_name: 'DSF', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 6,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 7,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 8,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 9,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 10,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 11,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 12,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 13,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 14,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 15,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 16,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
    { id: 17,field_name: 'NDE', sport: 'football', main_photo: 'NDE_main.png', address: 'RCGM+67M, Rd - 5, Dhaka 1229', city: 'Dhaka', slot_price: '5000 BDT', open_hours:'8:00 am - 9:00 pm', title_image:'',description: 'There are many variations of passages......', servicing_cost: '1000 BDT'},
];

export default field;